name: deploy
on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          submodules: recursive
          fetch-depth: 0
      - name: Checkout - read hash
        run: ./.github/read_hash.sh
      - name: Toolchain - rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Toolchain - nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Preprocessor - dependency + build
        run: cargo build --release --all-features
        working-directory: gust-gen
      - name: Data - build
        run: gust-gen/target/release/gust-gen ./gust-data ./public/gust_generated
      - name: Frontend - dependency
        run: yarn install --frozen-lockfile
      - name: Frontend - build
        run: yarn build
      - name: Frontend - upload
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Artifact - download
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Deploy - authenticate
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy
        run: |
          aws s3 cp ./build s3://${{ secrets.AWS_S3_BUCKET }} --recursive --exclude "*.md" --acl public-read
          aws s3 cp ./build s3://${{ secrets.AWS_S3_BUCKET }} --recursive --content-type text/markdown --metadata-directive REPLACE --exclude "*" --include "*.md" --acl public-read
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CF_DISTRIBUTION }} --paths "/*"
